# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

server_prefix='k8s'
boxes = [
    {
        :name => "#{server_prefix}111",
        :eth1 => "192.168.10.111",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "#{server_prefix}112",
        :eth1 => "192.168.10.112",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "#{server_prefix}113",
        :eth1 => "192.168.10.113",
        :mem => "1024",
        :cpu => "1"
    }
]

Vagrant.configure("2") do |config|
  # 设置虚拟机的Box
  config.vm.box = "base-vm-box"

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|

      # 设置虚拟机的主机名
      config.vm.hostname = opts[:name]
      config.ssh.insert_key = false

#       config.vm.provider "vmware_fusion" do |v|
#         v.vmx["memsize"] = opts[:mem]
#         v.vmx["numvcpus"] = opts[:cpu]
#       end
      config.vm.provider "virtualbox" do |v|
        v.name = opts[:name]
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end

      # 设置虚拟机的IP
      config.vm.network :private_network, ip: opts[:eth1]
    end
  end

  # Generic initialization
  config.vm.provision "shell", path: "scripts/start.sh"
end